insert into data_owner (code,classificatie,omschrijving) values
('CBSWS0152', 'Infra Beheerder', 'Waterschap Rijn En IJssel'),
('CBSWS0155', 'Infra Beheerder', 'Hoogheemraadschap Amstel Gooi En Vecht'),
('CBSWS0372', 'Infra Beheerder', 'Hoogheemraadschap Van Delfland'),
('CBSWS0539', 'Infra Beheerder', 'Waterschap De Dommel'),
('CBSWS0616', 'Infra Beheerder', 'Hoogheemraadschap Van Rijnland'),
('CBSWS0621', 'Infra Beheerder', 'Waterschap Rivierenland'),
('CBSWS0636', 'Infra Beheerder', 'Hoogheemraadschap De Stichtse Rijnlanden'),
('CBSWS0646', 'Infra Beheerder', 'Waterschap Hunze En Aa''s'),
('CBSWS0647', 'Infra Beheerder', 'Waterschap Noorderzijlvest'),
('CBSWS0650', 'Infra Beheerder', 'Waterschap Zuiderzeeland'),
('CBSWS0651', 'Infra Beheerder', 'Hoogheemraadschap Hollands Noorderkwartier'),
('CBSWS0652', 'Infra Beheerder', 'Waterschap Brabantse Delta'),
('CBSWS0653', 'Infra Beheerder', 'Wetterskip Fryslân'),
('CBSWS0654', 'Infra Beheerder', 'Waterschap Aa en Maas'),
('CBSWS0655', 'Infra Beheerder', 'Waterschap Hollandse Delta'),
('CBSWS0656', 'Infra Beheerder', 'Hoogheemraadschap van Schieland en Krimpenerwaard'),
('CBSWS0661', 'Infra Beheerder', 'Waterschap Scheldestromen'),
('CBSWS0662', 'Infra Beheerder', 'Waterschap Vallei en Veluwe'),
('CBSWS0663', 'Infra Beheerder', 'Waterschap Vechtstromen'),
('CBSWS0664', 'Infra Beheerder', 'Waterschap Drents Overijsselse Delta'),
('CBSWS0665', 'Infra Beheerder', 'Waterschap Limburg'),
('CBSWS0659', 'Infra Beheerder', 'Waterschapsbedrijf Limburg');