update data_owner set omschrijving = 'Rijkswaterstaat Bouw Dienst' where code = 'RWSBD';
update data_owner set omschrijving = 'Rijkswaterstaat Data en Informatie Dienst' where code = 'RWSDID';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst IJsselmeer Gebied' where code = 'RWSDIJG';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst Limburg' where code = 'RWSDLB';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst Noord-Brabant' where code = 'RWSDNB';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst Noord-Holland' where code = 'RWSDNH';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst Noord-Nederland' where code = 'RWSDNN';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst Noordzee' where code = 'RWSDNZ';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst Oost-Nederland' where code = 'RWSDON';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst Utrecht' where code = 'RWSDUT';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst Verkeer en Scheepvaart' where code = 'RWSDVS';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst Zuid-Holland' where code = 'RWSDZH';
update data_owner set omschrijving = 'Rijkswaterstaat Dienst Zeeland' where code = 'RWSDZL';
update data_owner set omschrijving = 'Rijkswaterstaat Water Dienst' where code = 'RWSWD';
