-- nav "20090527 DataOwnercodes.xls"

insert into data_owner (code, type, name, description, validation_required) values ('BRU','COPR','Bestuur Regio Utrecht','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('DR','COPR','Drente','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('FLV','COPR','Flevoland','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('FR','COPR','Friesland','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('GLD','COPR','Gelderland','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('GR','COPR','Provincie Groningen ','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('KAN','COPR','Stadsregio Arnhem Nijmegen','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('LIM','COPR','Limburg','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('NB','COPR','Noord Brabant','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('OVS','COPR','Overijssel','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('PNH','COPR','Noord Holland','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('PUTR','COPR','Provincie Utrecht','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('PZH','COPR','Zuid Holland','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('RT','COPR','Regio Twente','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('SGH','COPR','Stadsgewest Haaglanden','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('SRA','COPR','Stadsregio Amsterdam','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('SRE','COPR','Samenwerkingsverband regio Eindhoven','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('SRR','COPR','Stadsregio Rotterdam','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('ZLD','COPR','Zeeland','OV autoriteit',false);
insert into data_owner (code, type, name, description, validation_required) values ('0003','ROOW','Appingedam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0005','ROOW','Bedum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0007','ROOW','Bellingwedde',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0009','ROOW','Ten Boer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0010','ROOW','Delfzijl',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0014','ROOW','Groningen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0015','ROOW','Grootegast',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0017','ROOW','Haren',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0018','ROOW','Hoogezand-Sappemeer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0022','ROOW','Leek',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0024','ROOW','Loppersum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0025','ROOW','Marum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0034','ROOW','Almere',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0037','ROOW','Stadskanaal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0039','ROOW','Scheemda',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0040','ROOW','Slochteren',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0047','ROOW','Veendam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0048','ROOW','Vlagtwedde',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0050','ROOW','Zeewolde',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0051','ROOW','Skarsterlân',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0052','ROOW','Winschoten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0053','ROOW','Winsum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0055','ROOW','Boarnsterhim',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0056','ROOW','Zuidhorn',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0058','ROOW','Dongeradeel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0059','ROOW','Achtkarspelen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0060','ROOW','Ameland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0063','ROOW','het Bildt',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0064','ROOW','Bolsward',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0065','ROOW','Dantumadeel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0070','ROOW','Franekeradeel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0072','ROOW','Harlingen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0074','ROOW','Heerenveen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0079','ROOW','Kollumerland en Nieuwkruisland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0080','ROOW','Leeuwarden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0081','ROOW','Leeuwarderadeel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0082','ROOW','Lemsterland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0083','ROOW','Menaldumadeel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0085','ROOW','Ooststellingwerf',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0086','ROOW','Opsterland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0088','ROOW','Schiermonnikoog',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0090','ROOW','Smallingerland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0091','ROOW','Sneek',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0093','ROOW','Terschelling',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0096','ROOW','Vlieland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0098','ROOW','Weststellingwerf',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0104','ROOW','Nijefurd',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0106','ROOW','Assen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0109','ROOW','Coevorden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0114','ROOW','Emmen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0118','ROOW','Hoogeveen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0119','ROOW','Meppel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0140','ROOW','Littenseradiel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0141','ROOW','Almelo',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0147','ROOW','Borne',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0148','ROOW','Dalfsen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0150','ROOW','Deventer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0153','ROOW','Enschede',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0158','ROOW','Haaksbergen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0160','ROOW','Hardenberg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0163','ROOW','Hellendoorn',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0164','ROOW','Hengelo',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0166','ROOW','Kampen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0168','ROOW','Losser',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0171','ROOW','Noordoostpolder',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0173','ROOW','Oldenzaal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0175','ROOW','Ommen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0177','ROOW','Raalte',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0180','ROOW','Staphorst',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0183','ROOW','Tubbergen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0184','ROOW','Urk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0189','ROOW','Wierden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0193','ROOW','Zwolle',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0196','ROOW','Rijnwaarden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0197','ROOW','Aalten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0200','ROOW','Apeldoorn',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0202','ROOW','Arnhem',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0203','ROOW','Barneveld',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0209','ROOW','Beuningen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0213','ROOW','Brummen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0214','ROOW','Buren',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0216','ROOW','Culemborg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0221','ROOW','Doesburg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0222','ROOW','Doetinchem',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0225','ROOW','Druten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0226','ROOW','Duiven',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0228','ROOW','Ede',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0230','ROOW','Elburg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0232','ROOW','Epe',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0233','ROOW','Ermelo',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0236','ROOW','Geldermalsen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0241','ROOW','Groesbeek',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0243','ROOW','Harderwijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0244','ROOW','Hattem',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0246','ROOW','Heerde',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0252','ROOW','Heumen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0262','ROOW','Lochem',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0263','ROOW','Maasdriel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0265','ROOW','Millingen aan de Rijn',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0267','ROOW','Nijkerk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0268','ROOW','Nijmegen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0269','ROOW','Oldebroek',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0273','ROOW','Putten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0274','ROOW','Renkum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0275','ROOW','Rheden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0277','ROOW','Rozendaal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0279','ROOW','Scherpenzeel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0281','ROOW','Tiel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0282','ROOW','Ubbergen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0285','ROOW','Voorst',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0289','ROOW','Wageningen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0293','ROOW','Westervoort',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0294','ROOW','Winterswijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0296','ROOW','Wijchen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0297','ROOW','Zaltbommel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0299','ROOW','Zevenaar',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0301','ROOW','Zutphen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0302','ROOW','Nunspeet',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0303','ROOW','Dronten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0304','ROOW','Neerijnen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0305','ROOW','Abcoude',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0307','ROOW','Amersfoort',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0308','ROOW','Baarn',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0310','ROOW','De Bilt',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0311','ROOW','Breukelen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0312','ROOW','Bunnik',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0313','ROOW','Bunschoten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0317','ROOW','Eemnes',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0321','ROOW','Houten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0327','ROOW','Leusden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0329','ROOW','Loenen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0331','ROOW','Lopik',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0333','ROOW','Maarssen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0335','ROOW','Montfoort',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0339','ROOW','Renswoude',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0340','ROOW','Rhenen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0342','ROOW','Soest',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0344','ROOW','Utrecht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0345','ROOW','Veenendaal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0351','ROOW','Woudenberg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0352','ROOW','Wijk bij Duurstede',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0353','ROOW','IJsselstein',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0355','ROOW','Zeist',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0356','ROOW','Nieuwegein',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0358','ROOW','Aalsmeer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0361','ROOW','Alkmaar',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0362','ROOW','Amstelveen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0363','ROOW','Amsterdam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0364','ROOW','Andijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0365','ROOW','Graft-De Rijp',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0366','ROOW','Anna Paulowna',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0370','ROOW','Beemster',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0372','ROOW','Bennebroek',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0373','ROOW','Bergen (NH.)',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0375','ROOW','Beverwijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0376','ROOW','Blaricum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0377','ROOW','Bloemendaal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0381','ROOW','Bussum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0383','ROOW','Castricum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0384','ROOW','Diemen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0385','ROOW','Edam-Volendam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0388','ROOW','Enkhuizen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0392','ROOW','Haarlem',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0393','ROOW','Haarlemmerliede en Spaarnwoude',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0394','ROOW','Haarlemmermeer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0395','ROOW','Harenkarspel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0396','ROOW','Heemskerk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0397','ROOW','Heemstede',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0398','ROOW','Heerhugowaard',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0399','ROOW','Heiloo',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0400','ROOW','Den Helder',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0402','ROOW','Hilversum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0405','ROOW','Hoorn',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0406','ROOW','Huizen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0412','ROOW','Niedorp',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0415','ROOW','Landsmeer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0416','ROOW','Langedijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0417','ROOW','Laren',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0420','ROOW','Medemblik',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0424','ROOW','Muiden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0425','ROOW','Naarden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0431','ROOW','Oostzaan',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0432','ROOW','Opmeer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0437','ROOW','Ouder-Amstel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0439','ROOW','Purmerend',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0441','ROOW','Schagen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0448','ROOW','Texel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0450','ROOW','Uitgeest',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0451','ROOW','Uithoorn',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0453','ROOW','Velsen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0457','ROOW','Weesp',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0458','ROOW','Schermer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0459','ROOW','Wervershoof',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0462','ROOW','Wieringen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0463','ROOW','Wieringermeer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0473','ROOW','Zandvoort',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0476','ROOW','Zijpe',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0478','ROOW','Zeevang',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0479','ROOW','Zaanstad',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0482','ROOW','Alblasserdam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0483','ROOW','Alkemade',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0484','ROOW','Alphen aan den Rijn',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0489','ROOW','Barendrecht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0491','ROOW','Bergambacht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0497','ROOW','Bodegraven',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0498','ROOW','Drechterland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0499','ROOW','Boskoop',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0501','ROOW','Brielle',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0502','ROOW','Capelle aan den IJssel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0503','ROOW','Delft',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0504','ROOW','Dirksland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0505','ROOW','Dordrecht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0511','ROOW','Goedereede',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0512','ROOW','Gorinchem',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0513','ROOW','Gouda',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0518','ROOW','''s-Gravenhage',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0523','ROOW','Hardinxveld-Giessendam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0530','ROOW','Hellevoetsluis',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0531','ROOW','Hendrik-Ido-Ambacht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0532','ROOW','Stede Broec',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0534','ROOW','Hillegom',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0537','ROOW','Katwijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0542','ROOW','Krimpen aan den IJssel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0545','ROOW','Leerdam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0546','ROOW','Leiden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0547','ROOW','Leiderdorp',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0553','ROOW','Lisse',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0556','ROOW','Maassluis',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0559','ROOW','Middelharnis',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0563','ROOW','Moordrecht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0567','ROOW','Nieuwerkerk aan den IJssel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0568','ROOW','Bernisse',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0569','ROOW','Nieuwkoop',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0571','ROOW','Nieuw-Lekkerland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0575','ROOW','Noordwijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0576','ROOW','Noordwijkerhout',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0579','ROOW','Oegstgeest',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0580','ROOW','Oostflakkee',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0584','ROOW','Oud-Beijerland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0585','ROOW','Binnenmaas',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0588','ROOW','Korendijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0589','ROOW','Oudewater',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0590','ROOW','Papendrecht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0595','ROOW','Reeuwijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0597','ROOW','Ridderkerk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0599','ROOW','Rotterdam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0600','ROOW','Rozenburg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0603','ROOW','Rijswijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0606','ROOW','Schiedam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0608','ROOW','Schoonhoven',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0610','ROOW','Sliedrecht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0611','ROOW','Cromstrijen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0612','ROOW','Spijkenisse',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0613','ROOW','Albrandswaard',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0614','ROOW','Westvoorne',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0617','ROOW','Strijen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0620','ROOW','Vianen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0622','ROOW','Vlaardingen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0623','ROOW','Vlist',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0626','ROOW','Voorschoten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0627','ROOW','Waddinxveen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0629','ROOW','Wassenaar',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0632','ROOW','Woerden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0637','ROOW','Zoetermeer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0638','ROOW','Zoeterwoude',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0642','ROOW','Zwijndrecht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0643','ROOW','Nederlek',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0644','ROOW','Ouderkerk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0645','ROOW','Jacobswoude',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0653','ROOW','Gaasterlân-Sleat',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0654','ROOW','Borsele',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0664','ROOW','Goes',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0668','ROOW','West Maas en Waal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0677','ROOW','Hulst',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0678','ROOW','Kapelle',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0683','ROOW','Wymbritseradiel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0687','ROOW','Middelburg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0689','ROOW','Giessenlanden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0693','ROOW','Graafstroom',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0694','ROOW','Liesveld',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0703','ROOW','Reimerswaal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0707','ROOW','Zederik',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0710','ROOW','Wûnseradiel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0715','ROOW','Terneuzen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0716','ROOW','Tholen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0717','ROOW','Veere',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0718','ROOW','Vlissingen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0733','ROOW','Lingewaal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0736','ROOW','De Ronde Venen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0737','ROOW','Tytsjerksteradiel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0738','ROOW','Aalburg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0743','ROOW','Asten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0744','ROOW','Baarle-Nassau',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0748','ROOW','Bergen op Zoom',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0753','ROOW','Best',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0755','ROOW','Boekel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0756','ROOW','Boxmeer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0757','ROOW','Boxtel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0758','ROOW','Breda',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0762','ROOW','Deurne',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0765','ROOW','Pekela',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0766','ROOW','Dongen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0770','ROOW','Eersel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0772','ROOW','Eindhoven',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0777','ROOW','Etten-Leur',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0779','ROOW','Geertruidenberg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0784','ROOW','Gilze en Rijen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0785','ROOW','Goirle',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0786','ROOW','Grave',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0788','ROOW','Haaren',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0794','ROOW','Helmond',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0796','ROOW','''s-Hertogenbosch',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0797','ROOW','Heusden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0798','ROOW','Hilvarenbeek',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0808','ROOW','Lith',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0809','ROOW','Loon op Zand',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0815','ROOW','Mill en Sint Hubert',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0820','ROOW','Nuenen, Gerwen en Nederwetten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0823','ROOW','Oirschot',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0824','ROOW','Oisterwijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0826','ROOW','Oosterhout',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0828','ROOW','Oss',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0840','ROOW','Rucphen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0844','ROOW','Schijndel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0845','ROOW','Sint-Michielsgestel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0846','ROOW','Sint-Oedenrode',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0847','ROOW','Someren',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0848','ROOW','Son en Breugel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0851','ROOW','Steenbergen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0852','ROOW','Waterland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0855','ROOW','Tilburg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0856','ROOW','Uden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0858','ROOW','Valkenswaard',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0860','ROOW','Veghel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0861','ROOW','Veldhoven',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0865','ROOW','Vught',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0866','ROOW','Waalre',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0867','ROOW','Waalwijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0870','ROOW','Werkendam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0873','ROOW','Woensdrecht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0874','ROOW','Woudrichem',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0879','ROOW','Zundert',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0880','ROOW','Wormerland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0881','ROOW','Onderbanken',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0882','ROOW','Landgraaf',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0885','ROOW','Arcen en Velden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0888','ROOW','Beek',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0889','ROOW','Beesel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0893','ROOW','Bergen (L.)',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0899','ROOW','Brunssum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0905','ROOW','Eijsden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0907','ROOW','Gennep',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0917','ROOW','Heerlen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0918','ROOW','Helden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0928','ROOW','Kerkrade',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0929','ROOW','Kessel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0934','ROOW','Maasbree',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0935','ROOW','Maastricht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0936','ROOW','Margraten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0938','ROOW','Meerssen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0941','ROOW','Meijel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0944','ROOW','Mook en Middelaar',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0946','ROOW','Nederweert',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0951','ROOW','Nuth',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0957','ROOW','Roermond',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0962','ROOW','Schinnen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0964','ROOW','Sevenum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0965','ROOW','Simpelveld',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0971','ROOW','Stein',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0981','ROOW','Vaals',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0983','ROOW','Venlo',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0984','ROOW','Venray',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0986','ROOW','Voerendaal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0988','ROOW','Weert',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0993','ROOW','Meerlo-Wanssum',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0994','ROOW','Valkenburg aan de Geul',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('0995','ROOW','Lelystad',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1507','ROOW','Horst aan de Maas',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1509','ROOW','Oude IJsselstreek',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1525','ROOW','Teylingen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1581','ROOW','Utrechtse Heuvelrug',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1586','ROOW','Oost Gelre',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1598','ROOW','Koggenland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1621','ROOW','Lansingerland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1640','ROOW','Leudal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1641','ROOW','Maasgouw',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1651','ROOW','Eemsmond',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1652','ROOW','Gemert-Bakel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1655','ROOW','Halderberge',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1658','ROOW','Heeze-Leende',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1659','ROOW','Laarbeek',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1661','ROOW','Reiderland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1663','ROOW','De Marne',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1666','ROOW','Zevenhuizen-Moerkapelle',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1667','ROOW','Reusel-De Mierden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1669','ROOW','Roerdalen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1671','ROOW','Maasdonk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1672','ROOW','Rijnwoude',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1674','ROOW','Roosendaal',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1676','ROOW','Schouwen-Duiveland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1680','ROOW','Aa en Hunze',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1681','ROOW','Borger-Odoorn',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1684','ROOW','Cuijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1685','ROOW','Landerd',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1690','ROOW','De Wolden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1695','ROOW','Noord-Beveland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1696','ROOW','Wijdemeren',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1699','ROOW','Noordenveld',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1700','ROOW','Twenterand',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1701','ROOW','Westerveld',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1702','ROOW','Sint Anthonis',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1705','ROOW','Lingewaard',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1706','ROOW','Cranendonck',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1708','ROOW','Steenwijkerland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1709','ROOW','Moerdijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1711','ROOW','Echt-Susteren',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1714','ROOW','Sluis',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1719','ROOW','Drimmelen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1721','ROOW','Bernheze',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1722','ROOW','Ferwerderadiel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1723','ROOW','Alphen-Chaam',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1724','ROOW','Bergeijk',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1728','ROOW','Bladel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1729','ROOW','Gulpen-Wittem',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1730','ROOW','Tynaarlo',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1731','ROOW','Midden-Drenthe',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1734','ROOW','Overbetuwe',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1735','ROOW','Hof van Twente',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1740','ROOW','Neder-Betuwe',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1742','ROOW','Rijssen-Holten',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1771','ROOW','Geldrop-Mierlo',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1773','ROOW','Olst-Wijhe',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1774','ROOW','Dinkelland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1783','ROOW','Westland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1842','ROOW','Midden-Delfland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1859','ROOW','Berkelland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1876','ROOW','Bronckhorst',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1883','ROOW','Sittard-Geleen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1896','ROOW','Zwartewaterland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1916','ROOW','Leidschendam-Voorburg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1926','ROOW','Pijnacker-Nootdorp',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1955','ROOW','Montferland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('1987','ROOW','Menterwolde',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2151','ROOW','Waterschap Groot Salland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2152','ROOW','Waterschap Rijn en IJssel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2153','ROOW','Waterschap Veluwe',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2154','ROOW','Waterschap Vallei en Eem',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2155','ROOW','Hoogheemraadschap Amstel Gooi en Vecht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2201','ROOW','Waterschap Regge en Dinkel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2267','ROOW','Waterschap Groot Haarlemmermeer',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2368','ROOW','Waterschap de Brielse Dijkring',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2372','ROOW','Hoogheemraadschap van Delfland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2400','ROOW','Waterschap de Groote Waard',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2419','ROOW','Hoogheemraadschap van de Krimpenerwaard',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2467','ROOW','Hoogheemraadschap van Schieland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2498','ROOW','Waterschap Ijsselmonde',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2515','ROOW','Waterschap Goeree Overflakkee',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2516','ROOW','Zuiveringsschap Hollandse Eilanden en Waarden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2517','ROOW','Hoogheemraadschap van de Alblasserwaard en de Vijfheerenland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2519','ROOW','Waterschap Wilck en Wiericke',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2524','ROOW','Waterschap Zeeuwsch Vlaanderen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2535','ROOW','Hoogheemraadschap Alm en Biesbosch',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2536','ROOW','Waterschap Zeeuwse Eilanden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2539','ROOW','Waterschap de Dommel',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2584','ROOW','Zuiveringschap Limburg',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2585','ROOW','Waterschap Roer en Overmaas',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2616','ROOW','Hoogheemraadschap van Rijnland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2621','ROOW','Waterschap Rivierenland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2635','ROOW','Waterschap de Oude Rijnstromen',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2636','ROOW','Hoogheemraadschap de Stichtse Rijnlanden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2638','ROOW','Waterschap Peel en Maasvallei',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2646','ROOW','Waterschap Hunze en Aa''s',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2647','ROOW','Waterschap Noorderzijlvest',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2648','ROOW','Waterschap Reest en Wieden',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2649','ROOW','Waterschap Velt en Vecht',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2650','ROOW','Waterschap Zuiderzeeland',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2651','ROOW','Hoogheemraadschap Hollands Noorderkwartier',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2652','ROOW','Waterschap Brabantse Delta',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2653','ROOW','Wetterskip Fryslân',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('2654','ROOW','Waterschap Aa en Maas ',null,false);
insert into data_owner (code, type, name, description, validation_required) values ('A','ROOW','Groningen','Prov. Groningen, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('B','ROOW','Friesland','Prov. Friesland, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('D','ROOW','Drente','Prov. Drenthe, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('E','ROOW','Overijssel','Prov. Overijssel, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('G','ROOW','Gelderland','Prov. Gelderland, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('H','ROOW','Zuid Holland','Prov. Zuid Holland, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('K','ROOW','Limburg','Porv. Limburg, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('L','ROOW','Noord Holland','Prov. Noord Holland, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('M','ROOW','Utrecht','Prov. Utrecht, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('P','ROOW','Noord Brabant','Prov. Noord Brabant, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('S','ROOW','Zeeland','Prov. Zeeland, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('X','ROOW','Flevoland','Prov. Flevoland, wegbeheerder',false);
insert into data_owner (code, type, name, description, validation_required) values ('WSIJS','ROOW','IJsselmeergebied','Directie Rijkswaterstaat',false);
insert into data_owner (code, type, name, description, validation_required) values ('WSLB','ROOW','Limburg','Directie Rijkswaterstaat',false);
insert into data_owner (code, type, name, description, validation_required) values ('WSNB','ROOW','Noord Brabant','Directie Rijkswaterstaat',false);
insert into data_owner (code, type, name, description, validation_required) values ('WSNH','ROOW','Noord Holland','Directie Rijkswaterstaat',false);
insert into data_owner (code, type, name, description, validation_required) values ('WSNN','ROOW','Noord Nederland','Directie Rijkswaterstaat',false);
insert into data_owner (code, type, name, description, validation_required) values ('WSON','ROOW','Oost Nederland','Directie Rijkswaterstaat',false);
insert into data_owner (code, type, name, description, validation_required) values ('WSUT','ROOW','Utrecht','Directie Rijkswaterstaat',false);
insert into data_owner (code, type, name, description, validation_required) values ('WSZH','ROOW','Zuid Holland','Directie Rijkswaterstaat',false);
insert into data_owner (code, type, name, description, validation_required) values ('WSZL','ROOW','Zeeland','Directie Rijkswaterstaat',false);
