-- uitgecommentarieerde regels zijn duplicate keys!

insert into data_owner (code, type, name, description) values ('A','ROOW','Provincie Groningen', null);
insert into data_owner (code, type, name, description) values ('B','ROOW','Friesland', null);
insert into data_owner (code, type, name, description) values ('D','ROOW','Drente', null);
insert into data_owner (code, type, name, description) values ('E','ROOW','Overijssel', null);
insert into data_owner (code, type, name, description) values ('G','ROOW','Gelderland', null);
insert into data_owner (code, type, name, description) values ('H','ROOW','Zuid Holland', null);
insert into data_owner (code, type, name, description) values ('K','ROOW','Limburg', null);
insert into data_owner (code, type, name, description) values ('L','ROOW','Noord Holland', null);
insert into data_owner (code, type, name, description) values ('M','ROOW','Provincie Utrecht', null);
insert into data_owner (code, type, name, description) values ('P ','ROOW','Noord Brabant', null);
insert into data_owner (code, type, name, description) values ('S','ROOW','Zeeland', null);
insert into data_owner (code, type, name, description) values ('X ','ROOW','Flevoland', null);
insert into data_owner (code, type, name, description) values ('0003','ROOW','Appingedam', null);
insert into data_owner (code, type, name, description) values ('0005','ROOW','Bedum', null);
insert into data_owner (code, type, name, description) values ('0007','ROOW','Bellingwedde', null);
insert into data_owner (code, type, name, description) values ('0009','ROOW','Ten Boer', null);
insert into data_owner (code, type, name, description) values ('0010','ROOW','Delfzijl', null);
insert into data_owner (code, type, name, description) values ('0014','ROOW','Groningen', null);
insert into data_owner (code, type, name, description) values ('0015','ROOW','Grootegast', null);
insert into data_owner (code, type, name, description) values ('0017','ROOW','Haren', null);
insert into data_owner (code, type, name, description) values ('0018','ROOW','Hoogezand-Sappemeer', null);
insert into data_owner (code, type, name, description) values ('0022','ROOW','Leek', null);
insert into data_owner (code, type, name, description) values ('0024','ROOW','Loppersum', null);
insert into data_owner (code, type, name, description) values ('0025','ROOW','Marum', null);
insert into data_owner (code, type, name, description) values ('0034','ROOW','Almere', null);
insert into data_owner (code, type, name, description) values ('0037','ROOW','Stadskanaal', null);
insert into data_owner (code, type, name, description) values ('0039','ROOW','Scheemda', null);
insert into data_owner (code, type, name, description) values ('0040','ROOW','Slochteren', null);
insert into data_owner (code, type, name, description) values ('0047','ROOW','Veendam', null);
insert into data_owner (code, type, name, description) values ('0048','ROOW','Vlagtwedde', null);
insert into data_owner (code, type, name, description) values ('0050','ROOW','Zeewolde', null);
insert into data_owner (code, type, name, description) values ('0051','ROOW','Skarsterlân', null);
insert into data_owner (code, type, name, description) values ('0052','ROOW','Winschoten', null);
insert into data_owner (code, type, name, description) values ('0053','ROOW','Winsum', null);
insert into data_owner (code, type, name, description) values ('0055','ROOW','Boarnsterhim', null);
insert into data_owner (code, type, name, description) values ('0056','ROOW','Zuidhorn', null);
insert into data_owner (code, type, name, description) values ('0058','ROOW','Dongeradeel', null);
insert into data_owner (code, type, name, description) values ('0059','ROOW','Achtkarspelen', null);
insert into data_owner (code, type, name, description) values ('0060','ROOW','Ameland', null);
insert into data_owner (code, type, name, description) values ('0063','ROOW','het Bildt', null);
insert into data_owner (code, type, name, description) values ('0064','ROOW','Bolsward', null);
insert into data_owner (code, type, name, description) values ('0065','ROOW','Dantumadeel', null);
insert into data_owner (code, type, name, description) values ('0070','ROOW','Franekeradeel', null);
insert into data_owner (code, type, name, description) values ('0072','ROOW','Harlingen', null);
insert into data_owner (code, type, name, description) values ('0074','ROOW','Heerenveen', null);
insert into data_owner (code, type, name, description) values ('0079','ROOW','Kollumerland en Nieuwkruisland', null);
insert into data_owner (code, type, name, description) values ('0080','ROOW','Leeuwarden', null);
insert into data_owner (code, type, name, description) values ('0081','ROOW','Leeuwarderadeel', null);
insert into data_owner (code, type, name, description) values ('0082','ROOW','Lemsterland', null);
insert into data_owner (code, type, name, description) values ('0083','ROOW','Menaldumadeel', null);
insert into data_owner (code, type, name, description) values ('0085','ROOW','Ooststellingwerf', null);
insert into data_owner (code, type, name, description) values ('0086','ROOW','Opsterland', null);
insert into data_owner (code, type, name, description) values ('0088','ROOW','Schiermonnikoog', null);
insert into data_owner (code, type, name, description) values ('0090','ROOW','Smallingerland', null);
insert into data_owner (code, type, name, description) values ('0091','ROOW','Sneek', null);
insert into data_owner (code, type, name, description) values ('0093','ROOW','Terschelling', null);
insert into data_owner (code, type, name, description) values ('0096','ROOW','Vlieland', null);
insert into data_owner (code, type, name, description) values ('0098','ROOW','Weststellingwerf', null);
insert into data_owner (code, type, name, description) values ('0104','ROOW','Nijefurd', null);
insert into data_owner (code, type, name, description) values ('0106','ROOW','Assen', null);
insert into data_owner (code, type, name, description) values ('0109','ROOW','Coevorden', null);
insert into data_owner (code, type, name, description) values ('0114','ROOW','Emmen', null);
insert into data_owner (code, type, name, description) values ('0118','ROOW','Hoogeveen', null);
insert into data_owner (code, type, name, description) values ('0119','ROOW','Meppel', null);
insert into data_owner (code, type, name, description) values ('0140','ROOW','Littenseradiel', null);
insert into data_owner (code, type, name, description) values ('0141','ROOW','Almelo', null);
insert into data_owner (code, type, name, description) values ('0147','ROOW','Borne', null);
insert into data_owner (code, type, name, description) values ('0148','ROOW','Dalfsen', null);
insert into data_owner (code, type, name, description) values ('0150','ROOW','Deventer', null);
insert into data_owner (code, type, name, description) values ('0151','ROOW','Waterschap Groot Salland','Waterschap');
insert into data_owner (code, type, name, description) values ('0152','ROOW','Waterschap Rijn en IJssel','Waterschap');
insert into data_owner (code, type, name, description) values ('0153','ROOW','Enschede', null);
--insert into data_owner (code, type, name, description) values ('0153','ROOW','Waterschap Veluwe','Waterschap');
insert into data_owner (code, type, name, description) values ('0154','ROOW','Waterschap Vallei en Eem','Waterschap');
insert into data_owner (code, type, name, description) values ('0155','ROOW','Hoogheemraadschap Amstel Gooi en Vecht','Waterschap');
insert into data_owner (code, type, name, description) values ('0158','ROOW','Haaksbergen', null);
insert into data_owner (code, type, name, description) values ('0160','ROOW','Hardenberg', null);
insert into data_owner (code, type, name, description) values ('0163','ROOW','Hellendoorn', null);
insert into data_owner (code, type, name, description) values ('0164','ROOW','Hengelo', null);
insert into data_owner (code, type, name, description) values ('0166','ROOW','Kampen', null);
insert into data_owner (code, type, name, description) values ('0168','ROOW','Losser', null);
insert into data_owner (code, type, name, description) values ('0171','ROOW','Noordoostpolder', null);
insert into data_owner (code, type, name, description) values ('0173','ROOW','Oldenzaal', null);
insert into data_owner (code, type, name, description) values ('0175','ROOW','Ommen', null);
insert into data_owner (code, type, name, description) values ('0177','ROOW','Raalte', null);
insert into data_owner (code, type, name, description) values ('0180','ROOW','Staphorst', null);
insert into data_owner (code, type, name, description) values ('0183','ROOW','Tubbergen', null);
insert into data_owner (code, type, name, description) values ('0184','ROOW','Urk', null);
insert into data_owner (code, type, name, description) values ('0189','ROOW','Wierden', null);
insert into data_owner (code, type, name, description) values ('0193','ROOW','Zwolle', null);
insert into data_owner (code, type, name, description) values ('0196','ROOW','Rijnwaarden', null);
insert into data_owner (code, type, name, description) values ('0197','ROOW','Aalten', null);
insert into data_owner (code, type, name, description) values ('0200','ROOW','Apeldoorn', null);
insert into data_owner (code, type, name, description) values ('0201','ROOW','Waterschap Regge en Dinkel','Waterschap');
insert into data_owner (code, type, name, description) values ('0202','ROOW','Arnhem', null);
insert into data_owner (code, type, name, description) values ('0203','ROOW','Barneveld', null);
insert into data_owner (code, type, name, description) values ('0209','ROOW','Beuningen', null);
insert into data_owner (code, type, name, description) values ('0213','ROOW','Brummen', null);
insert into data_owner (code, type, name, description) values ('0214','ROOW','Buren', null);
insert into data_owner (code, type, name, description) values ('0216','ROOW','Culemborg', null);
insert into data_owner (code, type, name, description) values ('0221','ROOW','Doesburg', null);
insert into data_owner (code, type, name, description) values ('0222','ROOW','Doetinchem', null);
insert into data_owner (code, type, name, description) values ('0225','ROOW','Druten', null);
insert into data_owner (code, type, name, description) values ('0226','ROOW','Duiven', null);
insert into data_owner (code, type, name, description) values ('0228','ROOW','Ede', null);
insert into data_owner (code, type, name, description) values ('0230','ROOW','Elburg', null);
insert into data_owner (code, type, name, description) values ('0232','ROOW','Epe', null);
insert into data_owner (code, type, name, description) values ('0233','ROOW','Ermelo', null);
insert into data_owner (code, type, name, description) values ('0236','ROOW','Geldermalsen', null);
insert into data_owner (code, type, name, description) values ('0241','ROOW','Groesbeek', null);
insert into data_owner (code, type, name, description) values ('0243','ROOW','Harderwijk', null);
insert into data_owner (code, type, name, description) values ('0244','ROOW','Hattem', null);
insert into data_owner (code, type, name, description) values ('0246','ROOW','Heerde', null);
insert into data_owner (code, type, name, description) values ('0252','ROOW','Heumen', null);
insert into data_owner (code, type, name, description) values ('0262','ROOW','Lochem', null);
insert into data_owner (code, type, name, description) values ('0263','ROOW','Maasdriel', null);
insert into data_owner (code, type, name, description) values ('0265','ROOW','Millingen aan de Rijn', null);
insert into data_owner (code, type, name, description) values ('0267','ROOW','Nijkerk', null);
--insert into data_owner (code, type, name, description) values ('0267','ROOW','Waterschap Groot Haarlemmermeer','Waterschap');
insert into data_owner (code, type, name, description) values ('0268','ROOW','Nijmegen', null);
insert into data_owner (code, type, name, description) values ('0269','ROOW','Oldebroek', null);
insert into data_owner (code, type, name, description) values ('0273','ROOW','Putten', null);
insert into data_owner (code, type, name, description) values ('0274','ROOW','Renkum', null);
insert into data_owner (code, type, name, description) values ('0275','ROOW','Rheden', null);
insert into data_owner (code, type, name, description) values ('0277','ROOW','Rozendaal', null);
insert into data_owner (code, type, name, description) values ('0279','ROOW','Scherpenzeel', null);
insert into data_owner (code, type, name, description) values ('0281','ROOW','Tiel', null);
insert into data_owner (code, type, name, description) values ('0282','ROOW','Ubbergen', null);
insert into data_owner (code, type, name, description) values ('0285','ROOW','Voorst', null);
insert into data_owner (code, type, name, description) values ('0289','ROOW','Wageningen', null);
insert into data_owner (code, type, name, description) values ('0293','ROOW','Westervoort', null);
insert into data_owner (code, type, name, description) values ('0294','ROOW','Winterswijk', null);
insert into data_owner (code, type, name, description) values ('0296','ROOW','Wijchen', null);
insert into data_owner (code, type, name, description) values ('0297','ROOW','Zaltbommel', null);
insert into data_owner (code, type, name, description) values ('0299','ROOW','Zevenaar', null);
insert into data_owner (code, type, name, description) values ('0301','ROOW','Zutphen', null);
insert into data_owner (code, type, name, description) values ('0302','ROOW','Nunspeet', null);
insert into data_owner (code, type, name, description) values ('0303','ROOW','Dronten', null);
insert into data_owner (code, type, name, description) values ('0304','ROOW','Neerijnen', null);
insert into data_owner (code, type, name, description) values ('0305','ROOW','Abcoude', null);
insert into data_owner (code, type, name, description) values ('0307','ROOW','Amersfoort', null);
insert into data_owner (code, type, name, description) values ('0308','ROOW','Baarn', null);
insert into data_owner (code, type, name, description) values ('0310','ROOW','De Bilt', null);
insert into data_owner (code, type, name, description) values ('0311','ROOW','Breukelen', null);
insert into data_owner (code, type, name, description) values ('0312','ROOW','Bunnik', null);
insert into data_owner (code, type, name, description) values ('0313','ROOW','Bunschoten', null);
insert into data_owner (code, type, name, description) values ('0317','ROOW','Eemnes', null);
insert into data_owner (code, type, name, description) values ('0321','ROOW','Houten', null);
insert into data_owner (code, type, name, description) values ('0327','ROOW','Leusden', null);
insert into data_owner (code, type, name, description) values ('0329','ROOW','Loenen', null);
insert into data_owner (code, type, name, description) values ('0331','ROOW','Lopik', null);
insert into data_owner (code, type, name, description) values ('0333','ROOW','Maarssen', null);
insert into data_owner (code, type, name, description) values ('0335','ROOW','Montfoort', null);
insert into data_owner (code, type, name, description) values ('0339','ROOW','Renswoude', null);
insert into data_owner (code, type, name, description) values ('0340','ROOW','Rhenen', null);
insert into data_owner (code, type, name, description) values ('0342','ROOW','Soest', null);
insert into data_owner (code, type, name, description) values ('0344','ROOW','Utrecht', null);
insert into data_owner (code, type, name, description) values ('0345','ROOW','Veenendaal', null);
insert into data_owner (code, type, name, description) values ('0351','ROOW','Woudenberg', null);
insert into data_owner (code, type, name, description) values ('0352','ROOW','Wijk bij Duurstede', null);
insert into data_owner (code, type, name, description) values ('0353','ROOW','IJsselstein', null);
insert into data_owner (code, type, name, description) values ('0355','ROOW','Zeist', null);
insert into data_owner (code, type, name, description) values ('0356','ROOW','Nieuwegein', null);
insert into data_owner (code, type, name, description) values ('0358','ROOW','Aalsmeer', null);
insert into data_owner (code, type, name, description) values ('0361','ROOW','Alkmaar', null);
insert into data_owner (code, type, name, description) values ('0362','ROOW','Amstelveen', null);
insert into data_owner (code, type, name, description) values ('0363','ROOW','Amsterdam', null);
insert into data_owner (code, type, name, description) values ('0364','ROOW','Andijk', null);
insert into data_owner (code, type, name, description) values ('0365','ROOW','Graft-De Rijp', null);
insert into data_owner (code, type, name, description) values ('0366','ROOW','Anna Paulowna', null);
insert into data_owner (code, type, name, description) values ('0368','ROOW','Waterschap de Brielse Dijkring','Waterschap');
insert into data_owner (code, type, name, description) values ('0370','ROOW','Beemster', null);
insert into data_owner (code, type, name, description) values ('0372','ROOW','Bennebroek', null);
--insert into data_owner (code, type, name, description) values ('0372','ROOW','Hoogheemraadschap van Delfland ','Waterschap');
insert into data_owner (code, type, name, description) values ('0373','ROOW','Bergen (NH.)', null);
insert into data_owner (code, type, name, description) values ('0375','ROOW','Beverwijk', null);
insert into data_owner (code, type, name, description) values ('0376','ROOW','Blaricum', null);
insert into data_owner (code, type, name, description) values ('0377','ROOW','Bloemendaal', null);
insert into data_owner (code, type, name, description) values ('0381','ROOW','Bussum', null);
insert into data_owner (code, type, name, description) values ('0383','ROOW','Castricum', null);
insert into data_owner (code, type, name, description) values ('0384','ROOW','Diemen', null);
insert into data_owner (code, type, name, description) values ('0385','ROOW','Edam-Volendam', null);
insert into data_owner (code, type, name, description) values ('0388','ROOW','Enkhuizen', null);
insert into data_owner (code, type, name, description) values ('0392','ROOW','Haarlem', null);
insert into data_owner (code, type, name, description) values ('0393','ROOW','Haarlemmerliede en Spaarnwoude', null);
insert into data_owner (code, type, name, description) values ('0394','ROOW','Haarlemmermeer', null);
insert into data_owner (code, type, name, description) values ('0395','ROOW','Harenkarspel', null);
insert into data_owner (code, type, name, description) values ('0396','ROOW','Heemskerk', null);
insert into data_owner (code, type, name, description) values ('0397','ROOW','Heemstede', null);
insert into data_owner (code, type, name, description) values ('0398','ROOW','Heerhugowaard', null);
insert into data_owner (code, type, name, description) values ('0399','ROOW','Heiloo', null);
insert into data_owner (code, type, name, description) values ('0400','ROOW','Den Helder', null);
--insert into data_owner (code, type, name, description) values ('0400','ROOW','Waterschap de Groote Waard','Waterschap');
insert into data_owner (code, type, name, description) values ('0402','ROOW','Hilversum', null);
insert into data_owner (code, type, name, description) values ('0405','ROOW','Hoorn', null);
insert into data_owner (code, type, name, description) values ('0406','ROOW','Huizen', null);
insert into data_owner (code, type, name, description) values ('0412','ROOW','Niedorp', null);
insert into data_owner (code, type, name, description) values ('0415','ROOW','Landsmeer', null);
insert into data_owner (code, type, name, description) values ('0416','ROOW','Langedijk', null);
insert into data_owner (code, type, name, description) values ('0417','ROOW','Laren', null);
insert into data_owner (code, type, name, description) values ('0419','ROOW','Hoogheemraadschap van de Krimpenerwaard','Waterschap');
insert into data_owner (code, type, name, description) values ('0420','ROOW','Medemblik', null);
insert into data_owner (code, type, name, description) values ('0424','ROOW','Muiden', null);
insert into data_owner (code, type, name, description) values ('0425','ROOW','Naarden', null);
insert into data_owner (code, type, name, description) values ('0431','ROOW','Oostzaan', null);
insert into data_owner (code, type, name, description) values ('0432','ROOW','Opmeer', null);
insert into data_owner (code, type, name, description) values ('0437','ROOW','Ouder-Amstel', null);
insert into data_owner (code, type, name, description) values ('0439','ROOW','Purmerend', null);
insert into data_owner (code, type, name, description) values ('0441','ROOW','Schagen', null);
insert into data_owner (code, type, name, description) values ('0448','ROOW','Texel', null);
insert into data_owner (code, type, name, description) values ('0450','ROOW','Uitgeest', null);
insert into data_owner (code, type, name, description) values ('0451','ROOW','Uithoorn', null);
insert into data_owner (code, type, name, description) values ('0453','ROOW','Velsen', null);
insert into data_owner (code, type, name, description) values ('0457','ROOW','Weesp', null);
insert into data_owner (code, type, name, description) values ('0458','ROOW','Schermer', null);
insert into data_owner (code, type, name, description) values ('0459','ROOW','Wervershoof', null);
insert into data_owner (code, type, name, description) values ('0462','ROOW','Wieringen', null);
insert into data_owner (code, type, name, description) values ('0463','ROOW','Wieringermeer', null);
insert into data_owner (code, type, name, description) values ('0467','ROOW','Hoogheemraadschap van Schieland','Waterschap');
insert into data_owner (code, type, name, description) values ('0473','ROOW','Zandvoort', null);
insert into data_owner (code, type, name, description) values ('0476','ROOW','Zijpe', null);
insert into data_owner (code, type, name, description) values ('0478','ROOW','Zeevang', null);
insert into data_owner (code, type, name, description) values ('0479','ROOW','Zaanstad', null);
insert into data_owner (code, type, name, description) values ('0482','ROOW','Alblasserdam', null);
insert into data_owner (code, type, name, description) values ('0483','ROOW','Alkemade', null);
insert into data_owner (code, type, name, description) values ('0484','ROOW','Alphen aan den Rijn', null);
insert into data_owner (code, type, name, description) values ('0489','ROOW','Barendrecht', null);
insert into data_owner (code, type, name, description) values ('0491','ROOW','Bergambacht', null);
insert into data_owner (code, type, name, description) values ('0497','ROOW','Bodegraven', null);
insert into data_owner (code, type, name, description) values ('0498','ROOW','Drechterland', null);
--insert into data_owner (code, type, name, description) values ('0498','ROOW','Waterschap Ijsselmonde','Waterschap');
insert into data_owner (code, type, name, description) values ('0499','ROOW','Boskoop', null);
insert into data_owner (code, type, name, description) values ('0501','ROOW','Brielle', null);
insert into data_owner (code, type, name, description) values ('0502','ROOW','Capelle aan den IJssel', null);
insert into data_owner (code, type, name, description) values ('0503','ROOW','Delft', null);
insert into data_owner (code, type, name, description) values ('0504','ROOW','Dirksland', null);
insert into data_owner (code, type, name, description) values ('0505','ROOW','Dordrecht', null);
insert into data_owner (code, type, name, description) values ('0511','ROOW','Goedereede', null);
insert into data_owner (code, type, name, description) values ('0512','ROOW','Gorinchem', null);
insert into data_owner (code, type, name, description) values ('0513','ROOW','Gouda', null);
insert into data_owner (code, type, name, description) values ('0515','ROOW','Waterschap Goeree Overflakkee','Waterschap');
insert into data_owner (code, type, name, description) values ('0516','ROOW','Zuiveringsschap Hollandse Eilanden en Waarden','Waterschap');
insert into data_owner (code, type, name, description) values ('0517','ROOW','Hoogheemraadschap van de Alblasserwaard en de Vijfheerenland','Waterschap');
insert into data_owner (code, type, name, description) values ('0518','ROOW','''s-Gravenhage', null);
insert into data_owner (code, type, name, description) values ('0519','ROOW','Waterschap Wilck en Wiericke','Waterschap');
insert into data_owner (code, type, name, description) values ('0523','ROOW','Hardinxveld-Giessendam', null);
insert into data_owner (code, type, name, description) values ('0524','ROOW','Waterschap Zeeuwsch Vlaanderen','Waterschap');
insert into data_owner (code, type, name, description) values ('0530','ROOW','Hellevoetsluis', null);
insert into data_owner (code, type, name, description) values ('0531','ROOW','Hendrik-Ido-Ambacht', null);
insert into data_owner (code, type, name, description) values ('0532','ROOW','Stede Broec', null);
insert into data_owner (code, type, name, description) values ('0534','ROOW','Hillegom', null);
insert into data_owner (code, type, name, description) values ('0535','ROOW','Hoogheemraadschap Alm en Biesbosch','Waterschap');
insert into data_owner (code, type, name, description) values ('0536','ROOW','Waterschap Zeeuwse Eilanden','Waterschap');
insert into data_owner (code, type, name, description) values ('0537','ROOW','Katwijk', null);
insert into data_owner (code, type, name, description) values ('0539','ROOW','Waterschap de Dommel','Waterschap');
insert into data_owner (code, type, name, description) values ('0542','ROOW','Krimpen aan den IJssel', null);
insert into data_owner (code, type, name, description) values ('0545','ROOW','Leerdam', null);
insert into data_owner (code, type, name, description) values ('0546','ROOW','Leiden', null);
insert into data_owner (code, type, name, description) values ('0547','ROOW','Leiderdorp', null);
insert into data_owner (code, type, name, description) values ('0553','ROOW','Lisse', null);
insert into data_owner (code, type, name, description) values ('0556','ROOW','Maassluis', null);
insert into data_owner (code, type, name, description) values ('0559','ROOW','Middelharnis', null);
insert into data_owner (code, type, name, description) values ('0563','ROOW','Moordrecht', null);
insert into data_owner (code, type, name, description) values ('0567','ROOW','Nieuwerkerk aan den IJssel', null);
insert into data_owner (code, type, name, description) values ('0568','ROOW','Bernisse', null);
insert into data_owner (code, type, name, description) values ('0569','ROOW','Nieuwkoop', null);
insert into data_owner (code, type, name, description) values ('0571','ROOW','Nieuw-Lekkerland', null);
insert into data_owner (code, type, name, description) values ('0575','ROOW','Noordwijk', null);
insert into data_owner (code, type, name, description) values ('0576','ROOW','Noordwijkerhout', null);
insert into data_owner (code, type, name, description) values ('0579','ROOW','Oegstgeest', null);
insert into data_owner (code, type, name, description) values ('0580','ROOW','Oostflakkee', null);
insert into data_owner (code, type, name, description) values ('0584','ROOW','Oud-Beijerland', null);
--insert into data_owner (code, type, name, description) values ('0584','ROOW','Zuiveringschap Limburg','Waterschap');
insert into data_owner (code, type, name, description) values ('0585','ROOW','Binnenmaas', null);
--insert into data_owner (code, type, name, description) values ('0585','ROOW','Waterschap Roer en Overmaas','Waterschap');
insert into data_owner (code, type, name, description) values ('0588','ROOW','Korendijk', null);
insert into data_owner (code, type, name, description) values ('0589','ROOW','Oudewater', null);
insert into data_owner (code, type, name, description) values ('0590','ROOW','Papendrecht', null);
insert into data_owner (code, type, name, description) values ('0595','ROOW','Reeuwijk', null);
insert into data_owner (code, type, name, description) values ('0597','ROOW','Ridderkerk', null);
insert into data_owner (code, type, name, description) values ('0599','ROOW','Rotterdam', null);
insert into data_owner (code, type, name, description) values ('0600','ROOW','Rozenburg', null);
insert into data_owner (code, type, name, description) values ('0603','ROOW','Rijswijk', null);
insert into data_owner (code, type, name, description) values ('0606','ROOW','Schiedam', null);
insert into data_owner (code, type, name, description) values ('0608','ROOW','Schoonhoven', null);
insert into data_owner (code, type, name, description) values ('0610','ROOW','Sliedrecht', null);
insert into data_owner (code, type, name, description) values ('0611','ROOW','Cromstrijen', null);
insert into data_owner (code, type, name, description) values ('0612','ROOW','Spijkenisse', null);
insert into data_owner (code, type, name, description) values ('0613','ROOW','Albrandswaard', null);
insert into data_owner (code, type, name, description) values ('0614','ROOW','Westvoorne', null);
insert into data_owner (code, type, name, description) values ('0616','ROOW','Hoogheemraadschap van Rijnland','Waterschap');
insert into data_owner (code, type, name, description) values ('0617','ROOW','Strijen', null);
insert into data_owner (code, type, name, description) values ('0620','ROOW','Vianen', null);
insert into data_owner (code, type, name, description) values ('0621','ROOW','Waterschap Rivierenland','Waterschap');
insert into data_owner (code, type, name, description) values ('0622','ROOW','Vlaardingen', null);
insert into data_owner (code, type, name, description) values ('0623','ROOW','Vlist', null);
insert into data_owner (code, type, name, description) values ('0626','ROOW','Voorschoten', null);
insert into data_owner (code, type, name, description) values ('0627','ROOW','Waddinxveen', null);
insert into data_owner (code, type, name, description) values ('0629','ROOW','Wassenaar', null);
insert into data_owner (code, type, name, description) values ('0632','ROOW','Woerden', null);
insert into data_owner (code, type, name, description) values ('0635','ROOW','Waterschap de Oude Rijnstromen','Waterschap');
insert into data_owner (code, type, name, description) values ('0636','ROOW','Hoogheemraadschap de Stichtse Rijnlanden','Waterschap');
insert into data_owner (code, type, name, description) values ('0637','ROOW','Zoetermeer', null);
insert into data_owner (code, type, name, description) values ('0638','ROOW','Zoeterwoude', null);
--insert into data_owner (code, type, name, description) values ('0638','ROOW','Waterschap Peel en Maasvallei','Waterschap');
insert into data_owner (code, type, name, description) values ('0642','ROOW','Zwijndrecht', null);
insert into data_owner (code, type, name, description) values ('0643','ROOW','Nederlek', null);
insert into data_owner (code, type, name, description) values ('0644','ROOW','Ouderkerk', null);
insert into data_owner (code, type, name, description) values ('0645','ROOW','Jacobswoude', null);
insert into data_owner (code, type, name, description) values ('0646','ROOW','Waterschap Hunze en Aa''s','Waterschap');
insert into data_owner (code, type, name, description) values ('0647','ROOW','Waterschap Noorderzijlvest','Waterschap');
insert into data_owner (code, type, name, description) values ('0648','ROOW','Waterschap Reest en Wieden','Waterschap');
insert into data_owner (code, type, name, description) values ('0649','ROOW','Waterschap Velt en Vecht','Waterschap');
insert into data_owner (code, type, name, description) values ('0650','ROOW','Waterschap Zuiderzeeland','Waterschap');
insert into data_owner (code, type, name, description) values ('0651','ROOW','Hoogheemraadschap Hollands Noorderkwartier','Waterschap');
insert into data_owner (code, type, name, description) values ('0652','ROOW','Waterschap Brabantse Delta','Waterschap');
insert into data_owner (code, type, name, description) values ('0653','ROOW','Gaasterlân-Sleat', null);
--insert into data_owner (code, type, name, description) values ('0653','ROOW','Wetterskip Fryslân','Waterschap');
insert into data_owner (code, type, name, description) values ('0654','ROOW','Borsele', null);
--insert into data_owner (code, type, name, description) values ('0654','ROOW','Waterschap Aa en Maas ','Waterschap');
insert into data_owner (code, type, name, description) values ('0664','ROOW','Goes', null);
insert into data_owner (code, type, name, description) values ('0668','ROOW','West Maas en Waal', null);
insert into data_owner (code, type, name, description) values ('0677','ROOW','Hulst', null);
insert into data_owner (code, type, name, description) values ('0678','ROOW','Kapelle', null);
insert into data_owner (code, type, name, description) values ('0683','ROOW','Wymbritseradiel', null);
insert into data_owner (code, type, name, description) values ('0687','ROOW','Middelburg', null);
insert into data_owner (code, type, name, description) values ('0689','ROOW','Giessenlanden', null);
insert into data_owner (code, type, name, description) values ('0693','ROOW','Graafstroom', null);
insert into data_owner (code, type, name, description) values ('0694','ROOW','Liesveld', null);
insert into data_owner (code, type, name, description) values ('0703','ROOW','Reimerswaal', null);
insert into data_owner (code, type, name, description) values ('0707','ROOW','Zederik', null);
insert into data_owner (code, type, name, description) values ('0710','ROOW','Wûnseradiel', null);
insert into data_owner (code, type, name, description) values ('0715','ROOW','Terneuzen', null);
insert into data_owner (code, type, name, description) values ('0716','ROOW','Tholen', null);
insert into data_owner (code, type, name, description) values ('0717','ROOW','Veere', null);
insert into data_owner (code, type, name, description) values ('0718','ROOW','Vlissingen', null);
insert into data_owner (code, type, name, description) values ('0733','ROOW','Lingewaal', null);
insert into data_owner (code, type, name, description) values ('0736','ROOW','De Ronde Venen', null);
insert into data_owner (code, type, name, description) values ('0737','ROOW','Tytsjerksteradiel', null);
insert into data_owner (code, type, name, description) values ('0738','ROOW','Aalburg', null);
insert into data_owner (code, type, name, description) values ('0743','ROOW','Asten', null);
insert into data_owner (code, type, name, description) values ('0744','ROOW','Baarle-Nassau', null);
insert into data_owner (code, type, name, description) values ('0748','ROOW','Bergen op Zoom', null);
insert into data_owner (code, type, name, description) values ('0753','ROOW','Best', null);
insert into data_owner (code, type, name, description) values ('0755','ROOW','Boekel', null);
insert into data_owner (code, type, name, description) values ('0756','ROOW','Boxmeer', null);
insert into data_owner (code, type, name, description) values ('0757','ROOW','Boxtel', null);
insert into data_owner (code, type, name, description) values ('0758','ROOW','Breda', null);
insert into data_owner (code, type, name, description) values ('0762','ROOW','Deurne', null);
insert into data_owner (code, type, name, description) values ('0765','ROOW','Pekela', null);
insert into data_owner (code, type, name, description) values ('0766','ROOW','Dongen', null);
insert into data_owner (code, type, name, description) values ('0770','ROOW','Eersel', null);
insert into data_owner (code, type, name, description) values ('0772','ROOW','Eindhoven', null);
insert into data_owner (code, type, name, description) values ('0777','ROOW','Etten-Leur', null);
insert into data_owner (code, type, name, description) values ('0779','ROOW','Geertruidenberg', null);
insert into data_owner (code, type, name, description) values ('0784','ROOW','Gilze en Rijen', null);
insert into data_owner (code, type, name, description) values ('0785','ROOW','Goirle', null);
insert into data_owner (code, type, name, description) values ('0786','ROOW','Grave', null);
insert into data_owner (code, type, name, description) values ('0788','ROOW','Haaren', null);
insert into data_owner (code, type, name, description) values ('0794','ROOW','Helmond', null);
insert into data_owner (code, type, name, description) values ('0796','ROOW','''s-Hertogenbosch', null);
insert into data_owner (code, type, name, description) values ('0797','ROOW','Heusden', null);
insert into data_owner (code, type, name, description) values ('0798','ROOW','Hilvarenbeek', null);
insert into data_owner (code, type, name, description) values ('0808','ROOW','Lith', null);
insert into data_owner (code, type, name, description) values ('0809','ROOW','Loon op Zand', null);
insert into data_owner (code, type, name, description) values ('0815','ROOW','Mill en Sint Hubert', null);
insert into data_owner (code, type, name, description) values ('0820','ROOW','Nuenen, Gerwen en Nederwetten', null);
insert into data_owner (code, type, name, description) values ('0823','ROOW','Oirschot', null);
insert into data_owner (code, type, name, description) values ('0824','ROOW','Oisterwijk', null);
insert into data_owner (code, type, name, description) values ('0826','ROOW','Oosterhout', null);
insert into data_owner (code, type, name, description) values ('0828','ROOW','Oss', null);
insert into data_owner (code, type, name, description) values ('0840','ROOW','Rucphen', null);
insert into data_owner (code, type, name, description) values ('0844','ROOW','Schijndel', null);
insert into data_owner (code, type, name, description) values ('0845','ROOW','Sint-Michielsgestel', null);
insert into data_owner (code, type, name, description) values ('0846','ROOW','Sint-Oedenrode', null);
insert into data_owner (code, type, name, description) values ('0847','ROOW','Someren', null);
insert into data_owner (code, type, name, description) values ('0848','ROOW','Son en Breugel', null);
insert into data_owner (code, type, name, description) values ('0851','ROOW','Steenbergen', null);
insert into data_owner (code, type, name, description) values ('0852','ROOW','Waterland', null);
insert into data_owner (code, type, name, description) values ('0855','ROOW','Tilburg', null);
insert into data_owner (code, type, name, description) values ('0856','ROOW','Uden', null);
insert into data_owner (code, type, name, description) values ('0858','ROOW','Valkenswaard', null);
insert into data_owner (code, type, name, description) values ('0860','ROOW','Veghel', null);
insert into data_owner (code, type, name, description) values ('0861','ROOW','Veldhoven', null);
insert into data_owner (code, type, name, description) values ('0865','ROOW','Vught', null);
insert into data_owner (code, type, name, description) values ('0866','ROOW','Waalre', null);
insert into data_owner (code, type, name, description) values ('0867','ROOW','Waalwijk', null);
insert into data_owner (code, type, name, description) values ('0870','ROOW','Werkendam', null);
insert into data_owner (code, type, name, description) values ('0873','ROOW','Woensdrecht', null);
insert into data_owner (code, type, name, description) values ('0874','ROOW','Woudrichem', null);
insert into data_owner (code, type, name, description) values ('0879','ROOW','Zundert', null);
insert into data_owner (code, type, name, description) values ('0880','ROOW','Wormerland', null);
insert into data_owner (code, type, name, description) values ('0881','ROOW','Onderbanken', null);
insert into data_owner (code, type, name, description) values ('0882','ROOW','Landgraaf', null);
insert into data_owner (code, type, name, description) values ('0885','ROOW','Arcen en Velden', null);
insert into data_owner (code, type, name, description) values ('0888','ROOW','Beek', null);
insert into data_owner (code, type, name, description) values ('0889','ROOW','Beesel', null);
insert into data_owner (code, type, name, description) values ('0893','ROOW','Bergen (L.)', null);
insert into data_owner (code, type, name, description) values ('0899','ROOW','Brunssum', null);
insert into data_owner (code, type, name, description) values ('0905','ROOW','Eijsden', null);
insert into data_owner (code, type, name, description) values ('0907','ROOW','Gennep', null);
insert into data_owner (code, type, name, description) values ('0917','ROOW','Heerlen', null);
insert into data_owner (code, type, name, description) values ('0918','ROOW','Helden', null);
insert into data_owner (code, type, name, description) values ('0928','ROOW','Kerkrade', null);
insert into data_owner (code, type, name, description) values ('0929','ROOW','Kessel', null);
insert into data_owner (code, type, name, description) values ('0934','ROOW','Maasbree', null);
insert into data_owner (code, type, name, description) values ('0935','ROOW','Maastricht', null);
insert into data_owner (code, type, name, description) values ('0936','ROOW','Margraten', null);
insert into data_owner (code, type, name, description) values ('0938','ROOW','Meerssen', null);
insert into data_owner (code, type, name, description) values ('0941','ROOW','Meijel', null);
insert into data_owner (code, type, name, description) values ('0944','ROOW','Mook en Middelaar', null);
insert into data_owner (code, type, name, description) values ('0946','ROOW','Nederweert', null);
insert into data_owner (code, type, name, description) values ('0951','ROOW','Nuth', null);
insert into data_owner (code, type, name, description) values ('0957','ROOW','Roermond', null);
insert into data_owner (code, type, name, description) values ('0962','ROOW','Schinnen', null);
insert into data_owner (code, type, name, description) values ('0964','ROOW','Sevenum', null);
insert into data_owner (code, type, name, description) values ('0965','ROOW','Simpelveld', null);
insert into data_owner (code, type, name, description) values ('0971','ROOW','Stein', null);
insert into data_owner (code, type, name, description) values ('0981','ROOW','Vaals', null);
insert into data_owner (code, type, name, description) values ('0983','ROOW','Venlo', null);
insert into data_owner (code, type, name, description) values ('0984','ROOW','Venray', null);
insert into data_owner (code, type, name, description) values ('0986','ROOW','Voerendaal', null);
insert into data_owner (code, type, name, description) values ('0988','ROOW','Weert', null);
insert into data_owner (code, type, name, description) values ('0993','ROOW','Meerlo-Wanssum', null);
insert into data_owner (code, type, name, description) values ('0994','ROOW','Valkenburg aan de Geul', null);
insert into data_owner (code, type, name, description) values ('0995','ROOW','Lelystad', null);
insert into data_owner (code, type, name, description) values ('1507','ROOW','Horst aan de Maas', null);
insert into data_owner (code, type, name, description) values ('1509','ROOW','Oude IJsselstreek', null);
insert into data_owner (code, type, name, description) values ('1525','ROOW','Teylingen', null);
insert into data_owner (code, type, name, description) values ('1581','ROOW','Utrechtse Heuvelrug', null);
insert into data_owner (code, type, name, description) values ('1586','ROOW','Oost Gelre', null);
insert into data_owner (code, type, name, description) values ('1598','ROOW','Koggenland', null);
insert into data_owner (code, type, name, description) values ('1621','ROOW','Lansingerland', null);
insert into data_owner (code, type, name, description) values ('1640','ROOW','Leudal', null);
insert into data_owner (code, type, name, description) values ('1641','ROOW','Maasgouw', null);
insert into data_owner (code, type, name, description) values ('1651','ROOW','Eemsmond', null);
insert into data_owner (code, type, name, description) values ('1652','ROOW','Gemert-Bakel', null);
insert into data_owner (code, type, name, description) values ('1655','ROOW','Halderberge', null);
insert into data_owner (code, type, name, description) values ('1658','ROOW','Heeze-Leende', null);
insert into data_owner (code, type, name, description) values ('1659','ROOW','Laarbeek', null);
insert into data_owner (code, type, name, description) values ('1661','ROOW','Reiderland', null);
insert into data_owner (code, type, name, description) values ('1663','ROOW','De Marne', null);
insert into data_owner (code, type, name, description) values ('1666','ROOW','Zevenhuizen-Moerkapelle', null);
insert into data_owner (code, type, name, description) values ('1667','ROOW','Reusel-De Mierden', null);
insert into data_owner (code, type, name, description) values ('1669','ROOW','Roerdalen', null);
insert into data_owner (code, type, name, description) values ('1671','ROOW','Maasdonk', null);
insert into data_owner (code, type, name, description) values ('1672','ROOW','Rijnwoude', null);
insert into data_owner (code, type, name, description) values ('1674','ROOW','Roosendaal', null);
insert into data_owner (code, type, name, description) values ('1676','ROOW','Schouwen-Duiveland', null);
insert into data_owner (code, type, name, description) values ('1680','ROOW','Aa en Hunze', null);
insert into data_owner (code, type, name, description) values ('1681','ROOW','Borger-Odoorn', null);
insert into data_owner (code, type, name, description) values ('1684','ROOW','Cuijk', null);
insert into data_owner (code, type, name, description) values ('1685','ROOW','Landerd', null);
insert into data_owner (code, type, name, description) values ('1690','ROOW','De Wolden', null);
insert into data_owner (code, type, name, description) values ('1695','ROOW','Noord-Beveland', null);
insert into data_owner (code, type, name, description) values ('1696','ROOW','Wijdemeren', null);
insert into data_owner (code, type, name, description) values ('1699','ROOW','Noordenveld', null);
insert into data_owner (code, type, name, description) values ('1700','ROOW','Twenterand', null);
insert into data_owner (code, type, name, description) values ('1701','ROOW','Westerveld', null);
insert into data_owner (code, type, name, description) values ('1702','ROOW','Sint Anthonis', null);
insert into data_owner (code, type, name, description) values ('1705','ROOW','Lingewaard', null);
insert into data_owner (code, type, name, description) values ('1706','ROOW','Cranendonck', null);
insert into data_owner (code, type, name, description) values ('1708','ROOW','Steenwijkerland', null);
insert into data_owner (code, type, name, description) values ('1709','ROOW','Moerdijk', null);
insert into data_owner (code, type, name, description) values ('1711','ROOW','Echt-Susteren', null);
insert into data_owner (code, type, name, description) values ('1714','ROOW','Sluis', null);
insert into data_owner (code, type, name, description) values ('1719','ROOW','Drimmelen', null);
insert into data_owner (code, type, name, description) values ('1721','ROOW','Bernheze', null);
insert into data_owner (code, type, name, description) values ('1722','ROOW','Ferwerderadiel', null);
insert into data_owner (code, type, name, description) values ('1723','ROOW','Alphen-Chaam', null);
insert into data_owner (code, type, name, description) values ('1724','ROOW','Bergeijk', null);
insert into data_owner (code, type, name, description) values ('1728','ROOW','Bladel', null);
insert into data_owner (code, type, name, description) values ('1729','ROOW','Gulpen-Wittem', null);
insert into data_owner (code, type, name, description) values ('1730','ROOW','Tynaarlo', null);
insert into data_owner (code, type, name, description) values ('1731','ROOW','Midden-Drenthe', null);
insert into data_owner (code, type, name, description) values ('1734','ROOW','Overbetuwe', null);
insert into data_owner (code, type, name, description) values ('1735','ROOW','Hof van Twente', null);
insert into data_owner (code, type, name, description) values ('1740','ROOW','Neder-Betuwe', null);
insert into data_owner (code, type, name, description) values ('1742','ROOW','Rijssen-Holten', null);
insert into data_owner (code, type, name, description) values ('1771','ROOW','Geldrop-Mierlo', null);
insert into data_owner (code, type, name, description) values ('1773','ROOW','Olst-Wijhe', null);
insert into data_owner (code, type, name, description) values ('1774','ROOW','Dinkelland', null);
insert into data_owner (code, type, name, description) values ('1783','ROOW','Westland', null);
insert into data_owner (code, type, name, description) values ('1842','ROOW','Midden-Delfland', null);
insert into data_owner (code, type, name, description) values ('1859','ROOW','Berkelland', null);
insert into data_owner (code, type, name, description) values ('1876','ROOW','Bronckhorst', null);
insert into data_owner (code, type, name, description) values ('1883','ROOW','Sittard-Geleen', null);
insert into data_owner (code, type, name, description) values ('1896','ROOW','Zwartewaterland', null);
insert into data_owner (code, type, name, description) values ('1916','ROOW','Leidschendam-Voorburg', null);
insert into data_owner (code, type, name, description) values ('1926','ROOW','Pijnacker-Nootdorp', null);
insert into data_owner (code, type, name, description) values ('1955','ROOW','Montferland', null);
insert into data_owner (code, type, name, description) values ('1987','ROOW','Menterwolde', null);
insert into data_owner (code, type, name, description) values ('BRU','COPR','Bestuur Regio Utrecht', null);
insert into data_owner (code, type, name, description) values ('DR','COPR','Drente', null);
insert into data_owner (code, type, name, description) values ('FLV','COPR','Flevoland ', null);
insert into data_owner (code, type, name, description) values ('FR','COPR','Friesland', null);
insert into data_owner (code, type, name, description) values ('GLD','COPR','Gelderland', null);
insert into data_owner (code, type, name, description) values ('GR','COPR','Provincie Groningen', null);
insert into data_owner (code, type, name, description) values ('KAN','COPR','Stadsregio Arnhem Nijmegen', null);
insert into data_owner (code, type, name, description) values ('LIM','COPR','Limburg', null);
insert into data_owner (code, type, name, description) values ('NB','COPR','Noord Brabant', null);
insert into data_owner (code, type, name, description) values ('OVS','COPR','Overijssel', null);
insert into data_owner (code, type, name, description) values ('PNH','COPR','Noord Holland', null);
insert into data_owner (code, type, name, description) values ('PUTR','COPR','Provincie Utrecht', null);
insert into data_owner (code, type, name, description) values ('PZH','COPR','Zuid Holland', null);
insert into data_owner (code, type, name, description) values ('RT','COPR','Regio Twente', null);
insert into data_owner (code, type, name, description) values ('SGH','COPR','Stadsgewest Haaglanden', null);
insert into data_owner (code, type, name, description) values ('SRA','COPR','Stadsregio Amsterdam', null);
insert into data_owner (code, type, name, description) values ('SRE','COPR','Samenwerkingsverband regio Eindhoven', null);
insert into data_owner (code, type, name, description) values ('SRR','COPR','Stadsregio Rotterdam', null);
insert into data_owner (code, type, name, description) values ('WSIJS','ROOW','IJsselmeergebied','Directies Rijkswaterstaat');
insert into data_owner (code, type, name, description) values ('WSLB','ROOW','Limburg','Directies Rijkswaterstaat');
insert into data_owner (code, type, name, description) values ('WSNB','ROOW','Noord Brabant','Directies Rijkswaterstaat');
insert into data_owner (code, type, name, description) values ('WSNH','ROOW','Noord Holland','Directies Rijkswaterstaat');
insert into data_owner (code, type, name, description) values ('WSNN','ROOW','Noord Nederland','Directies Rijkswaterstaat');
insert into data_owner (code, type, name, description) values ('WSON','ROOW','RWS dir. Oost Nederland','Directies Rijkswaterstaat');
insert into data_owner (code, type, name, description) values ('WSUT','ROOW','RWS Utrecht','Directies Rijkswaterstaat');
insert into data_owner (code, type, name, description) values ('WSZH','ROOW','RWS Zuid Holland','Directies Rijkswaterstaat');
insert into data_owner (code, type, name, description) values ('WSZL','ROOW','RWS Zeeland','Directies Rijkswaterstaat');
insert into data_owner (code, type, name, description) values ('ZLD','COPR','Zeeland', null);
insert into data_owner (code, type, name, description) values ('GOVI','INT','Grenzeloze OV Informatie', null);
